// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_paintdevicewidget.cpp"
#include "EWIEGA46WW/moc_tab1cube.cpp"
#include "EWIEGA46WW/moc_tab2cylinder.cpp"
#include "EWIEGA46WW/moc_tab3triangularprism.cpp"
